name: truecaller_sdk_example
description: Demonstrates how to use the truecaller_sdk plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^5.3.2
  permission_handler: ^11.0.1
  uuid: ^4.1.0
  flutter:
    sdk: flutter

  truecaller_sdk:
    # When depending on this package from a real application you should use:
    #   truecaller_sdk: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version. 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
